#!/bin/sh
while true; do 
    DATE=$(date '+%a %Y-%m-%d %H:%M')
    BAT=$(acpi -b | awk -F'[ ,:]+' '{print substr($3,1,3), $4}')
    VOLUME=$(wpctl get-volume @DEFAULT_SINK@ | awk -F'[ ,:]+' '{print "Vol", substr($2, length($2)-1)}')
    if [ "$BAT" = "Not charging" ]; then
        BAT=$(acpi -b | awk -F'[ ,:]+' '{print "Tlp", $5}')
    fi
    xsetroot -name " $VOLUME | $BAT | $DATE "
    sleep 10
done
