#!/bin/bash

# Detect WM
if [[ -n "$HYPRLAND_INSTANCE_SIGNATURE" ]]; then
    WM="hypr"
elif [[ -n "$NIRI_SOCKET" ]]; then
    WM="niri"
else
    WM="unknown"
fi

# Toggle eww
if pgrep eww > /dev/null; then
    pkill eww
else
    if [[ "$WM" == "hypr" ]]; then
        $HOME/.bin/eww open hypr-bar
    elif [[ "$WM" == "niri" ]]; then
        $HOME/.bin/eww open niri-bar
    else
        echo "nothing to do"
    fi
fi
