#!/bin/bash

# get the active workspace. Returns just the number
active_workspace=$(hyprctl activeworkspace | grep "workspace" | awk '{print $3}')

workspaces() {

    # these have 10, just so I can ignore the 1st one and do 1 through 9
    w=(0 0 0 0 0 0 0 0 0 0)
    f=(0 0 0 0 0 0 0 0 0 0)
    s=(0 "○" "○" "○" "○" "○" "○" "○" "○" "○") 

    # Loop through workspaces 1 to 9 and check if they are occupied or empty
    for i in {1..9}; do
        # Check if the workspace is occupied
        if hyprctl workspaces | grep -A 1 "workspace ID $i" > /dev/null 2>&1; then
            w[$i]=1
        else
            w[$i]=0
        fi

        # set f(n) to true for active workspace
        if [[ "$i" -eq "$active_workspace" ]]; then
            f[$i]=1
        else
            f[$i]=0
        fi
    done
    
    # set symbol for active workspace
    s[$active_workspace]="●"

    echo 	"(box   :class \"workspaces\"	:orientation \"h\" :spacing 7 :space-evenly \"true\" :halign \"start\" (button :onclick \"hyprctl dispatch workspace 1\" :class  \"ws1${w[1]}${f[1]}\"   \"${s[1]}\") (button :onclick \"hyprctl dispatch workspace 2\"	:class	\"ws2${w[2]}${f[2]}\"   \"${s[2]}\") (button :onclick \"hyprctl dispatch workspace 3\"	:class	\"ws3${w[3]}${f[3]}\"	\"${s[3]}\") (button :onclick \"hyprctl dispatch workspace 4\"	:class	\"ws4${w[4]}${f[4]}\"	\"${s[4]}\") (button :onclick \"hyprctl dispatch workspace 5\"	:class	\"ws5${w[5]}${f[5]}\"	\"${s[5]}\") (button :onclick \"hyprctl dispatch workspace 6\"	:class	\"ws6${w[6]}${f[6]}\"	\"${s[6]}\") (button :onclick \"hyprctl dispatch workspace 7\"	:class	\"ws7${w[7]}${f[7]}\"	\"${s[7]}\") (button :onclick \"hyprctl dispatch workspace 8\"	:class	\"ws8${w[8]}${f[8]}\"	\"${s[8]}\") (button :onclick \"hyprctl dispatch workspace 9\"	:class	\"ws9${w[9]}${f[9]}\"	\"${s[9]}\"))" 
}

while true; do

    new_workspace=$(hyprctl activeworkspace | grep "workspace" | awk '{print $3}')

    if [ "$new_workspace" != "$active_workspace" ]; then
        active_workspace=$new_workspace
        workspaces
    fi

    sleep 0.5
done
